//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTravelApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirTravelEntities : DbContext
    {
		private static AirTravelEntities _context;
		public AirTravelEntities()
            : base("name=AirTravelEntities")
        {
        }

		public static AirTravelEntities GetContext()
		{
			if (_context == null)
			{
				_context = new AirTravelEntities();
			}
			return _context;
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComfortClass> ComfortClass { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<JetType> JetType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
