//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTravelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JetType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JetType()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int MaximumSeats { get; set; }
        public int SeatCapacityEconomy { get; set; }
        public int SeatCapacityBusiness { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
