//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTravelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public int FlightID { get; set; }
        public int ComfortClassID { get; set; }
        public int UserID { get; set; }
    
        public virtual ComfortClass ComfortClass { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual User User { get; set; }
    }
}
